apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-pipeline-demo.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "docker-pipeline-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "docker-pipeline-demo.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "{{ .Values.env.APP_ENV }}"
