apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-pipeline-demo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "docker-pipeline-demo.name" . }}
  ports:
    - port: 8080
      targetPort: 8080
